# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1infskKeDtUqVNHpVNmtEaxgTDNnZk70p
"""

FILEPATH = 'carsdatabase (1).xlsx'
dataframes=read_all_sheets_from_excel(FILEPATH)

# print each dataframe name
print("Dataframe keys of dataframes:" + ", ".join(dataframes.keys()))

for k, v in dataframes.items():
    # strip whitespace where possible from column names; need to check if isinstance(x, str) because some column names are numbers
    try:
        v = v.rename(columns=lambda x: x.strip() if isinstance(x, str) else x)
    except:
        pass

    # strip whitespace where possible from cells
    try:
        v = v.apply(lambda col: col.str.strip() if col.dtype == "object" else col)
    except:
        pass
    dataframes[k] = v
    print('dataframe: '+ k)
    print(v.head(15))